<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class KaryawanSeeder extends Seeder
{
    /**
     * Parse nama lengkap → first_name, last_name, username
     * Aturan username: nama1.nama2 (tanpa gelar, tanpa tanda baca)
     */
    private function parseNama(string $namaLengkap): array
    {
        $namaLengkap = trim($namaLengkap);
        $parts = preg_split('/\s+/', $namaLengkap);
        $firstName = $parts[0] ?? '';
        $lastName  = count($parts) >= 2 ? implode(' ', array_slice($parts, 1)) : '';

        // Potong di koma untuk buang gelar
        $namaUntukUsername = trim(explode(',', $namaLengkap)[0]);
        $partsUsername = preg_split('/\s+/', $namaUntukUsername);

        $w1 = preg_replace('/[^a-z0-9]/', '', strtolower($partsUsername[0] ?? ''));
        $w2 = isset($partsUsername[1]) ? preg_replace('/[^a-z0-9]/', '', strtolower($partsUsername[1])) : null;

        $username = ($w2 !== null && $w2 !== '') ? $w1 . '.' . $w2 : $w1;

        return compact('firstName', 'lastName', 'username');
    }

    private function makeUniqueUsername(string $base, array &$usedUsernames): string
    {
        $username = $base;
        $i = 2;
        while (in_array($username, $usedUsernames)) {
            $username = $base . $i++;
        }
        $usedUsernames[] = $username;
        return $username;
    }

    public function run(): void
    {
        $usedUsernames = [];

        $karyawan = [
            ['nip' => '20121789', 'nama' => 'ADE FIRMANSYAH', 'unit_kerja' => 'INSTALASI GIZI', 'posisi_pekerjaan' => 'COOK BOGA', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212831', 'nama' => 'ADE IRPAN, SKM', 'unit_kerja' => 'RUMAH TANGGA', 'posisi_pekerjaan' => 'KOORDINATOR RUMAH TANGGA', 'profesi' => 'NON MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '19950244', 'nama' => 'ADE SASMITA,SE', 'unit_kerja' => 'ADMIN UMUM & ALIH DAYA', 'posisi_pekerjaan' => 'KOORDINATOR ADMIN, PERIZINAN & OUTSOURSCHING', 'profesi' => 'NON MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20253041', 'nama' => 'AGUNG WIBOWO,. S.Ars', 'unit_kerja' => 'IPSRS', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20071152', 'nama' => 'AGUS DARAJAT, Dr, Sp.A, M.Kes', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'DOKTER SPESIALIS', 'profesi' => 'MEDIS', 'jabatan' => 'DOKTER SPESIALIS'],
            ['nip' => '20253038', 'nama' => 'AHMAD MAULANA APRYAWAN', 'unit_kerja' => 'INSTALASI LABORATORIUM', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20081261', 'nama' => 'AJENG PUSPA INDAH, S.KEP., NERS', 'unit_kerja' => 'MUTU', 'posisi_pekerjaan' => 'MUTU & KESELAMATAN PASIEN', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20020506', 'nama' => 'AJI SAPRUDIN', 'unit_kerja' => 'TRANSPORTASI & KURIR', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253031', 'nama' => 'ALFIAN KURNIAWAN', 'unit_kerja' => 'IPSRS', 'posisi_pekerjaan' => 'KOORDINATOR IPSRS', 'profesi' => 'NON MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20212789', 'nama' => 'AMARTIWI, S.Kep., Ners', 'unit_kerja' => 'NS 8', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB NS 8', 'profesi' => 'MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20242987', 'nama' => 'AMELIA SUSANTI, AMD., KES', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'TERAPIS GIGI & MULUT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20101508', 'nama' => 'ANASTASIA DIAN PARLINA, S.KEP., NERS', 'unit_kerja' => 'ICU', 'posisi_pekerjaan' => 'KOORDINATOR ICU', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20212774', 'nama' => 'ANDIKA DWIPRASOJO, AMD.KEP', 'unit_kerja' => 'INSTALASI GAWAT DARURAT', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212779', 'nama' => 'ANDI RENDRA HANDIKO, S.Tr', 'unit_kerja' => 'KTKA', 'posisi_pekerjaan' => 'OKUPASI TERAPI', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20232906', 'nama' => 'ANDRI IFTIYOKO, SH', 'unit_kerja' => 'MARKETING', 'posisi_pekerjaan' => 'KOORDINATOR SALES', 'profesi' => 'NON MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20202688', 'nama' => 'ANGGITA SEVI, S. Farm', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'TENAGA TEKNIS KEFARMASIAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253095', 'nama' => 'ANGGITA YULIANA PUTRI, S.KEP., NERS', 'unit_kerja' => 'NS 8', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212797', 'nama' => 'ANGGI WIDIASTUTI, S.Kep.,Ners', 'unit_kerja' => 'NICU & PICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202717', 'nama' => 'ANGGUN ASTRIANNA APRIANTI, AMK', 'unit_kerja' => 'NICU & PICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242961', 'nama' => 'ANISA OKTAVIANI, S. KEP., NERS', 'unit_kerja' => 'NS 8', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '19950208', 'nama' => 'ANNA SUHARDINING. S.KEP.,NS', 'unit_kerja' => 'ICU', 'posisi_pekerjaan' => 'KOORDINATOR ICU', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20222874', 'nama' => 'ANSHAR FAISAL ISMI', 'unit_kerja' => 'IT', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192664', 'nama' => 'ANTIKA PUTRI PRATAMI', 'unit_kerja' => 'SEKRETARIAT', 'posisi_pekerjaan' => 'SEKRETARIS MEDIS', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20222851', 'nama' => 'ARDELIA NURHAIDA, S.Farm', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'TENAGA TEKNIS KEFARMASIAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253039', 'nama' => 'ARI DAYOS TABAKWAN., S. KEP., NERS', 'unit_kerja' => 'ICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253004', 'nama' => 'ARINI VIANSARI., A.MD. KEP', 'unit_kerja' => 'MPP', 'posisi_pekerjaan' => 'MPP', 'profesi' => 'NON MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20253066', 'nama' => 'ARI NURYANI NAHAMPUAN S.KEP, NERS', 'unit_kerja' => 'NS 3', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253084', 'nama' => 'ARLIANA LESTARI, AMD. KEP', 'unit_kerja' => 'NS 1', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212784', 'nama' => 'ASEP SARIF HIDAYATULLOH, S.Tr', 'unit_kerja' => 'CASEMIX', 'posisi_pekerjaan' => 'PEREKAM MEDIS', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253077', 'nama' => 'AULIA MUNAJAT, S.KEP., NERS', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20222857', 'nama' => 'AULIA PUSPITA SARI, S.Farm', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'TENAGA TEKNIS KEFARMASIAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212787', 'nama' => 'AYU ANDIRA, AMD KEP', 'unit_kerja' => 'NS 4', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192549', 'nama' => 'AYU WULANDARI, AMK', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20071134', 'nama' => 'BAGYA HERMAWAN, BR.AMK', 'unit_kerja' => 'KAMAR OPERASI', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20030527', 'nama' => 'BAMBANG PRIYADI', 'unit_kerja' => 'PENGADAAN UMUM', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253028', 'nama' => 'BELADINNA ZALFA ZAHIRAH, S. KEP., NERS', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20061047', 'nama' => 'BENI YULIA, AMK', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB RAWAT JALAN', 'profesi' => 'MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20242978', 'nama' => 'BINAR SASONO,dr. Sp. KFR', 'unit_kerja' => 'REHABILITASI MEDIK', 'posisi_pekerjaan' => 'DOKTER PENANGGUNG JAWAB REHABILITASI MEDIK & KTKA', 'profesi' => 'MEDIS', 'jabatan' => 'DOKTER SPESIALIS'],
            ['nip' => '20061055', 'nama' => 'BUDI HARTANTO', 'unit_kerja' => 'KASIR', 'posisi_pekerjaan' => 'KOORDINATOR KASIR DAN PENTARIFAN', 'profesi' => 'NON MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20020495', 'nama' => 'BUYUNG HERMAWAN', 'unit_kerja' => 'MAINTENANCE', 'posisi_pekerjaan' => 'STAFF IPSRS', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253049', 'nama' => 'CHANDRA BHAKTI PERWIRA, DR', 'unit_kerja' => 'DOKTER JAGA', 'posisi_pekerjaan' => 'DOKTER UMUM', 'profesi' => 'MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20081257', 'nama' => 'CHRISMA ADRYANA ALBANDJAR,  Dr. Sp.An-KIC', 'unit_kerja' => 'ICU', 'posisi_pekerjaan' => 'DOKTER PENANGGUNG JAWAB ICU', 'profesi' => 'MEDIS', 'jabatan' => 'DOKTER SPESIALIS'],
            ['nip' => '20253078', 'nama' => 'CHUTTIA RAMADANTI, S.KEP., NERS', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202734', 'nama' => 'DEA RATNA PUSPITASARI, S.KEP.,NERS', 'unit_kerja' => 'NS 3', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253069', 'nama' => 'DELLA AYU PRATIWI, SE', 'unit_kerja' => 'KASIR', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20091387', 'nama' => 'DEVITA RIZKI AMELIANA, AMK', 'unit_kerja' => 'HEMODIALISA', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242929', 'nama' => 'DEWI KHANIA, A. Md. Kes. Rad', 'unit_kerja' => 'INSTALASI RADIOLOGI', 'posisi_pekerjaan' => 'RADIOGRAFER', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202706', 'nama' => 'DHESTY ANDHIANISA, AMD KEP', 'unit_kerja' => 'INSTALASI GAWAT DARURAT', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20050938', 'nama' => 'DHIKA PRAMESTIKA, S.Kep., Ns', 'unit_kerja' => 'MARKETING', 'posisi_pekerjaan' => 'KOORDINATOR CUSTOMER MANAGEMENT', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20222899', 'nama' => 'DIAH AYU SEKARNINGTYAS., A. MD. AK', 'unit_kerja' => 'KASIR', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
        ];

        $karyawan = array_merge($karyawan, [
            ['nip' => '20172362', 'nama' => 'DIANA ROSITA, AMK', 'unit_kerja' => 'NS 7', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20020550', 'nama' => 'DIAN MAHDIANI, S.Kep.,Ners', 'unit_kerja' => 'KAMAR OPERASI', 'posisi_pekerjaan' => 'KOORDINATOR KAMAR OPERASI', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20030642', 'nama' => 'DIAN MATSYIWATI PUTRI SARI, S.Kep., Ners', 'unit_kerja' => 'PPI', 'posisi_pekerjaan' => 'IPCN', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20192595', 'nama' => 'DIAN NURUL HIKMAH, AMD GIZI', 'unit_kerja' => 'INSTALASI GIZI', 'posisi_pekerjaan' => 'AHLI GIZI PRODUKSI', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20101523', 'nama' => 'DIAN YUSTINANDA,DR', 'unit_kerja' => 'DOKTER JAGA', 'posisi_pekerjaan' => 'KEPALA INSTALASI RAWAT JALAN, MCU & HD', 'profesi' => 'MEDIS', 'jabatan' => 'KEPALA UNIT/ INSTALASI'],
            ['nip' => '20202703', 'nama' => 'DIDI NARSIDI, S.FARM', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'TENAGA TEKNIS KEFARMASIAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20222871', 'nama' => 'DINDA ANNISA FITRI, S.GZ', 'unit_kerja' => 'INSTALASI GIZI', 'posisi_pekerjaan' => 'AHLI GIZI KLINIK', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192599', 'nama' => 'DINI HENDRAYANI, S.KEP., NERS', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253044', 'nama' => 'DWI ASTUTI, S.Psi', 'unit_kerja' => 'SDM', 'posisi_pekerjaan' => 'KOORDINATOR SDM & PAYROLL', 'profesi' => 'NON MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20101481', 'nama' => 'DWI IRMA SARI, S.Farm', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'TENAGA TEKNIS KEFARMASIAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20101532', 'nama' => 'DWI RETNO HANDAYANI,S.FARM,APT', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB FARMASI RAWAT JALAN', 'profesi' => 'MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '19960257', 'nama' => 'DYAH ISTIATI, S. KEP., NERS', 'unit_kerja' => 'NICU & PICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192592', 'nama' => 'EKA KURNIASARI., S.S', 'unit_kerja' => 'ADMISSION', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20040661', 'nama' => 'EKA SETIA WULANNINGSIH, S.Kep', 'unit_kerja' => 'NS 1', 'posisi_pekerjaan' => 'KOORDINATOR RAWAT INAP ALAMANDA', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20253087', 'nama' => 'ELFA DIAN AGUSTINA, S.FARM, APT.', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'KOORDINATOR FARMASI', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20253034', 'nama' => 'ELNI OKTAVIANI, DR', 'unit_kerja' => 'DOKTER JAGA', 'posisi_pekerjaan' => 'DOKTER UMUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192537', 'nama' => 'ELSA SHYLVIA JUNIAR, AMD KEP', 'unit_kerja' => 'NS 1', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20030601', 'nama' => 'EMELIA SAPTYA MURTININGSIH, AMK', 'unit_kerja' => 'KAMAR OPERASI', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202678', 'nama' => 'EMILLIA HASANAH, S.TR.KES', 'unit_kerja' => 'KTKA', 'posisi_pekerjaan' => 'FISIOTERAPI', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20061039', 'nama' => 'ENI SAKHNA, S.Kep.,Ners', 'unit_kerja' => 'PERINATOLOGI', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB RUANG BAYI SEHAT', 'profesi' => 'MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20101424', 'nama' => 'ERNA MINAYATINA, AMK', 'unit_kerja' => 'NICU & PICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20040830', 'nama' => 'ERNA SUNARNI, AMAK', 'unit_kerja' => 'INSTALASI LABORATORIUM', 'posisi_pekerjaan' => 'KOORDINATOR PELAYANAN LABORATORIUM & BDRS', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20253027', 'nama' => 'ERVINA FITRIANI', 'unit_kerja' => 'KAMAR OPERASI', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202695', 'nama' => 'ETI RAHMAWATI, AMD KEP', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20081221', 'nama' => 'ETI ROHAETI, AMKG', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'TERAPIS GIGI & MULUT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242968', 'nama' => 'EVA OKTOVIANA, AMK', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20020429', 'nama' => 'EVI MINTARSIH, AMK', 'unit_kerja' => 'CSSD', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB CSSD', 'profesi' => 'MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20192645', 'nama' => 'EVI WULANDARI., A. MD', 'unit_kerja' => 'KASIR', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192620', 'nama' => 'FACHRI GINANJAR., A. MD', 'unit_kerja' => 'AKUNTANSI & PAJAK', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192623', 'nama' => 'FACHRULREZA DJAEMI, AMD', 'unit_kerja' => 'REKAM MEDIS', 'posisi_pekerjaan' => 'PEREKAM MEDIS', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253007', 'nama' => 'FADHILAH ULFAH., S. FARM., APT', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'APOTEKER', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253085', 'nama' => 'FAIZA DWI RAMADANIA. S.TR.KES', 'unit_kerja' => 'INSTALASI KAMAR OPERASI', 'posisi_pekerjaan' => 'PENATA ANESTESI', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '19930083', 'nama' => 'FATMAWATI', 'unit_kerja' => 'SEKRETARIAT', 'posisi_pekerjaan' => 'SEKRETARIS DIREKTUR RS AZRA', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20222861', 'nama' => 'FEBI ANGGRAINI, AMD', 'unit_kerja' => 'KASIR', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20040861', 'nama' => 'FERA ASRILIA, AMK', 'unit_kerja' => 'HEMODIALISA', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253060', 'nama' => 'FERDY DANIEL LATUPUTTY. S.KEP.,NERS', 'unit_kerja' => 'NS 1', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192579', 'nama' => 'FERI ANGRIAWAN, S.Tr', 'unit_kerja' => 'REKAM MEDIS', 'posisi_pekerjaan' => 'PEREKAM MEDIS', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20232916', 'nama' => 'FIDA FIRDAUS PRIMIANDIKA', 'unit_kerja' => 'INSTALASI RADIOLOGI', 'posisi_pekerjaan' => 'RADIOGRAFER', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212812', 'nama' => 'FINA FAUZIYAH, S.KEP.,NERS', 'unit_kerja' => 'NS 8', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192646', 'nama' => 'FIRMAN HAFITHUDIN SYAH., A. MD', 'unit_kerja' => 'KEUANGAN', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20081218', 'nama' => 'FITRI WIJAYANTI,AM. KEB', 'unit_kerja' => 'KAMAR BERSALIN', 'posisi_pekerjaan' => 'STAF BIDAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20141999', 'nama' => 'FITRIYANI MEGAWATI, AMD PERKES', 'unit_kerja' => 'REKAM MEDIS', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20131947', 'nama' => 'GARSIANA SRI HASANAH, S.FARM. APT', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB FARMASI KLINIS', 'profesi' => 'MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20252999', 'nama' => 'GHANIS GUSVIRANTY BAYU, AMD. KEB', 'unit_kerja' => 'MARKETING', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253043', 'nama' => 'GRACIA, S.Kep. Ners', 'unit_kerja' => 'PERINATOLOGI', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20020466', 'nama' => 'HADI KURNIAWAN, S.M', 'unit_kerja' => 'KEUANGAN', 'posisi_pekerjaan' => 'KOORDINATOR ACCOUNT RECEIVABLE', 'profesi' => 'NON MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20202748', 'nama' => 'HADIN AZIZ ABDURROHMAN, S.Tr', 'unit_kerja' => 'REKAM MEDIS', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253089', 'nama' => 'HALIMATUSSA \'DIYAH WIDIASTI, S.TR.KES.', 'unit_kerja' => 'KTKA', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253014', 'nama' => 'HANIFA AZZAHRA., S. FARM., APT', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'APOTEKER', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20101421', 'nama' => 'HANIFAH WINIARTI, AMK', 'unit_kerja' => 'ICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20020431', 'nama' => 'HERI SILVIA, AMK', 'unit_kerja' => 'INSTALASI GAWAT DARURAT', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
        ]);

        $karyawan = array_merge($karyawan, [
            ['nip' => '20061012', 'nama' => 'HILDA NEVIKAYATI, AMK', 'unit_kerja' => 'INSTALASI GAWAT DARURAT', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242935', 'nama' => 'HUSNUL FUADAH, S. KEP.,NERS', 'unit_kerja' => 'NS 8', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242944', 'nama' => 'IDA ROSIDA, S. KEP., NERS', 'unit_kerja' => 'PERINATOLOGI', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212793', 'nama' => 'I DEWA AYU YUNITA PERMATA SARI, AMd Kep', 'unit_kerja' => 'NS 7', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20182466', 'nama' => 'IHAH SOLIHAH, S.Tr.Keb', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF BIDAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20071157', 'nama' => 'IKA PURNAMASARI, AMK', 'unit_kerja' => 'NS 2', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB NS 2', 'profesi' => 'MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20101510', 'nama' => 'IMELDA GRACE CAROLINA H, Dr', 'unit_kerja' => 'DOKTER JAGA', 'posisi_pekerjaan' => 'DOKTER UMUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192563', 'nama' => 'INDAH NURHASANAH, SE', 'unit_kerja' => 'ADMISSION', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20202687', 'nama' => 'INDAH TRIYANI', 'unit_kerja' => 'PENGADAAN UMUM', 'posisi_pekerjaan' => 'KOORDINATOR PENGADAAN UMUM', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20172271', 'nama' => 'INDI INDRIYANI,AMD KEP', 'unit_kerja' => 'NICU & PICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253097', 'nama' => 'INDIVI AHMAD, S.TR.FT', 'unit_kerja' => 'REHABILITASI MEDIK', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212842', 'nama' => 'INDRI NURAIDA HAMDIAH, S.KEP.,NERS', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20111641', 'nama' => 'INTAN ANANDA UTAMI, Amd OT', 'unit_kerja' => 'KTKA', 'posisi_pekerjaan' => 'KOORDINATOR REHABILITASI MEDIK & KTKA', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20253025', 'nama' => 'INTAN INDRI ARDIYANTI.,M.Tr.TGM', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'TERAPIS GIGI & MULUT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192598', 'nama' => 'IRAWATI KUMALA, S.KEP.,NERS', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '19990369', 'nama' => 'IRENE SRI SUMARNI, AM.KEB', 'unit_kerja' => 'KAMAR BERSALIN', 'posisi_pekerjaan' => 'KOORDINATOR KAMAR BERSALIN', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '19930060', 'nama' => 'IWAN SETIAWAN', 'unit_kerja' => 'CSSD', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192647', 'nama' => 'JAMALUDIN., A. MD', 'unit_kerja' => 'KEUANGAN', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20172359', 'nama' => 'KARTA WARDANA, SST.FT', 'unit_kerja' => 'KTKA', 'posisi_pekerjaan' => 'FISIOTERAPI', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '19950243', 'nama' => 'KARYANI', 'unit_kerja' => 'INSTALASI LABORATORIUM', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253096', 'nama' => 'KEISA KAMILA A.MD.KES', 'unit_kerja' => 'REHABILITASI MEDIK', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20121745', 'nama' => 'KHAERUL ANWAR RUDDIN', 'unit_kerja' => 'INSTALASI GIZI', 'posisi_pekerjaan' => 'COOK PASTRY', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '19960217', 'nama' => 'KHAIRUN NISA NURAKHYATI, S.Kep,Ns,MARS', 'unit_kerja' => 'SDM', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20192540', 'nama' => 'KHANZA RIRI ARISTIANI, S.Gz', 'unit_kerja' => 'INSTALASI GIZI', 'posisi_pekerjaan' => 'KOORDINATOR GIZI', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20040854', 'nama' => 'KRISTIANI, AMK', 'unit_kerja' => 'HEMODIALISA', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '19930156', 'nama' => 'KUSWADI', 'unit_kerja' => 'CSSD', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20071151', 'nama' => 'LAELAH MEITARNENGSIH, AMK', 'unit_kerja' => 'INSTALASI GAWAT DARURAT', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192617', 'nama' => 'LALA FADLIATUS SYAHADA., A. MD', 'unit_kerja' => 'KASIR', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20091398', 'nama' => 'LANI RAHAYU, S.Kep., Ns', 'unit_kerja' => 'NS 3', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20050986', 'nama' => 'LAYUNG SARI, S.Kep.,Ners', 'unit_kerja' => 'NICU & PICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20020426', 'nama' => 'LESTARI RUMIYANI, S.Kep., Ns', 'unit_kerja' => 'INSTALASI GAWAT DARURAT', 'posisi_pekerjaan' => 'KOORDINATOR INSTALASI GAWAT DARURAT', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20212791', 'nama' => 'LILIS, Amd Kep', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242969', 'nama' => 'LILIS MELDIANI, AMD. AK', 'unit_kerja' => 'INSTALASI LABORATORIUM', 'posisi_pekerjaan' => 'ANALIS LABORATORIUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20182440', 'nama' => 'LINDA ANNISA LISDIANI, AMD KEP', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253047', 'nama' => 'LIRA SUCI RAMADHAN', 'unit_kerja' => 'MARKETING', 'posisi_pekerjaan' => 'MARKETING', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20182442', 'nama' => 'LISNA WULAN OKTAVIA ARTANTI,  S.Kep.,Ners', 'unit_kerja' => 'PERINATOLOGI', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202733', 'nama' => 'LUFTI TRI WAHYUNI, AMK', 'unit_kerja' => 'NS 7', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20222892', 'nama' => 'LUKMAN HAKIM, S. Farm', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'TENAGA TEKNIS KEFARMASIAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253026', 'nama' => 'LUTFIAH NUR SHADRINA', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20020486', 'nama' => 'MAMAN TASMAN', 'unit_kerja' => 'KEUANGAN', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20040833', 'nama' => 'MAMAT', 'unit_kerja' => 'TRANSPORTASI & KURIR', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20182500', 'nama' => 'MARIA ULFA, AMD KEP', 'unit_kerja' => 'NS 7', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20263099', 'nama' => 'MARIA ULFA, AMD KEP', 'unit_kerja' => 'NS 7', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20182502', 'nama' => 'MARISA LENI PUTRI. AMK', 'unit_kerja' => 'KAMAR OPERASI', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212766', 'nama' => 'MARNI MUNAWAROH, AMD KEP', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253010', 'nama' => 'MARTA DWI CAHYA LESTARI., AMD., KES (RAD)', 'unit_kerja' => 'INSTALASI RADIOLOGI', 'posisi_pekerjaan' => 'RADIOGRAFER', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202719', 'nama' => 'MEILIA RATNAPURI, AMD KEP', 'unit_kerja' => 'NS 7', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253065', 'nama' => 'MILA RAHMAWATI A.MD.RMIK', 'unit_kerja' => 'REKAM MEDIS', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253094', 'nama' => 'MIRANTI, S.KEP., NERS', 'unit_kerja' => 'NS 1', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20020458', 'nama' => 'M MAHFUD ISRO, S.E', 'unit_kerja' => 'KEUANGAN', 'posisi_pekerjaan' => 'SUPERVISOR KEUANGAN & ADMINISTRASI', 'profesi' => 'NON MEDIS', 'jabatan' => 'SUPERVISOR'],
        ]);

        $karyawan = array_merge($karyawan, [
            ['nip' => '20212825', 'nama' => 'MOCHAMAD RYAN DWI PRATAMA PUTRA, SE', 'unit_kerja' => 'KASIR', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20061042', 'nama' => 'MOCH IRFAN FIRDAUS., A. MD', 'unit_kerja' => 'CASEMIX', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20020422', 'nama' => 'MOHAMAD DANDI KURNIAWAN, S.Tr.Kes', 'unit_kerja' => 'REHABILITASI MEDIK', 'posisi_pekerjaan' => 'FISIOTERAPI', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20020488', 'nama' => 'MOHAMMAD PATI SIDIK', 'unit_kerja' => 'SDM', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253024', 'nama' => 'MONE RIZKI DESANDRY', 'unit_kerja' => 'MARKETING', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20030525', 'nama' => 'MUHAMAD OKY PATI IDRIS', 'unit_kerja' => 'KEUANGAN', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20172398', 'nama' => 'MUHAMMAD ARDYANSYAH PRATAMA, DR', 'unit_kerja' => 'DOKTER JAGA', 'posisi_pekerjaan' => 'KEPALA INSTALASI GAWAT DARURAT', 'profesi' => 'MEDIS', 'jabatan' => 'KEPALA UNIT/ INSTALASI'],
            ['nip' => '20253023', 'nama' => 'MUHAMMAD FARHAN SETIAWAN., S.TR. KES', 'unit_kerja' => 'INSTALASI KAMAR OPERASI', 'posisi_pekerjaan' => 'PENATA ANESTESI', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242963', 'nama' => 'MUHAMMAD FHADLUL SYAHRI, A.MD. KES', 'unit_kerja' => 'REHABILITASI MEDIK', 'posisi_pekerjaan' => 'TERAPI WICARA', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202676', 'nama' => 'MUHAMMAD HUSNUL KHULUQ, S.Ak', 'unit_kerja' => 'KASIR', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20172382', 'nama' => 'MUHAMMAD LAZUARDI E, AMK', 'unit_kerja' => 'KAMAR OPERASI', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20101450', 'nama' => 'MUIZAR', 'unit_kerja' => 'TRANSPORTASI & KURIR', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB TRANSPORTASI & KURIR', 'profesi' => 'NON MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20182443', 'nama' => 'MUKHFI, AMD OT', 'unit_kerja' => 'KTKA', 'posisi_pekerjaan' => 'OKUPASI TERAPI', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202746', 'nama' => 'MULTAZAM SIDDIQ S, AMd KES', 'unit_kerja' => 'INSTALASI RADIOLOGI', 'posisi_pekerjaan' => 'RADIOGRAFER', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20222877', 'nama' => 'MUTIARA AULIYAH SAFITRI, S.Kep.,Ners', 'unit_kerja' => 'INSTALASI GAWAT DARURAT', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '19990365', 'nama' => 'MUTIARA MARDIJJAH., S.I. Kom', 'unit_kerja' => 'MARKETING', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20222885', 'nama' => 'NADIA RIZKIANA PUTRI, S.Tr.Kes', 'unit_kerja' => 'REHABILITASI MEDIK', 'posisi_pekerjaan' => 'FISIOTERAPI', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242977', 'nama' => 'NADILAH DWITA LESTARI, AMD. KES', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'TERAPIS GIGI & MULUT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242953', 'nama' => 'NENENG NURJANAH, Amd. TW', 'unit_kerja' => 'KTKA', 'posisi_pekerjaan' => 'TERAPI WICARA', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253076', 'nama' => 'NGAKIF MUZAHID, AMD.T', 'unit_kerja' => 'IPSRS', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB PERALATAN MEDIS', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20081255', 'nama' => 'NIA TRY RAHAYU AGUSTINI, AMK', 'unit_kerja' => 'NS 2', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242950', 'nama' => 'NIDA KHAIRUNNISA, S.Tr. Ds', 'unit_kerja' => 'MARKETING', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20040752', 'nama' => 'N. IDA LAELA RUBIANTI, AMK', 'unit_kerja' => 'DUTY OFFICER', 'posisi_pekerjaan' => 'DUTY OFFICER', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20202721', 'nama' => 'NIDA USSA\'ADAH, AMD KEP', 'unit_kerja' => 'ICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202709', 'nama' => 'NOVI EKA ANDRIYANI, S.FARM., APT', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB FARMASI RAWAT INAP', 'profesi' => 'MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20192621', 'nama' => 'NOVI YANTI, A. MD', 'unit_kerja' => 'KEUANGAN', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253092', 'nama' => 'NURABILLA MAHARANI CAYADEWI S.TR.KEP., NERS', 'unit_kerja' => 'NS 4', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253063', 'nama' => 'NUR HALIMAH NASUTION, S.KEP., NERS', 'unit_kerja' => 'NS 1', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20030567', 'nama' => 'NURHASAN', 'unit_kerja' => 'MAINTENANCE', 'posisi_pekerjaan' => 'STAFF IPSRS', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20050944', 'nama' => 'NURHASANAH, Amd TW', 'unit_kerja' => 'KTKA', 'posisi_pekerjaan' => 'TERAPI WICARA', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253011', 'nama' => 'NURIKA IRFIYANI., AMD. TLM', 'unit_kerja' => 'INSTALASI LABORATORIUM', 'posisi_pekerjaan' => 'ANALIS LABORATORIUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242954', 'nama' => 'NURI NUR PADILAH, S. KEP., NERS', 'unit_kerja' => 'NS 8', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202735', 'nama' => 'NURJANAH, AMKEB', 'unit_kerja' => 'KAMAR BERSALIN', 'posisi_pekerjaan' => 'STAF BIDAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20081216', 'nama' => 'NURLELA, Amd TW', 'unit_kerja' => 'KTKA', 'posisi_pekerjaan' => 'TERAPI WICARA', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253082', 'nama' => 'NUR RAVICA APRILIA, S. KEP., NERS', 'unit_kerja' => 'NS 4', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20081292', 'nama' => 'NUR ULFA DEWI, AMK', 'unit_kerja' => 'INSTALASI GAWAT DARURAT', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212777', 'nama' => 'NURUL INDRIYANI, A Md. KEP', 'unit_kerja' => 'NS 8', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202711', 'nama' => 'NURUL SOBAH, AMD. FARM', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'TENAGA TEKNIS KEFARMASIAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242939', 'nama' => 'OPI DAMAHYANTI, S.FARM., APT', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'APOTEKER', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253081', 'nama' => 'PAHLEVI MARVELINO SIBORUTOROP., DR', 'unit_kerja' => 'DOKTER JAGA', 'posisi_pekerjaan' => 'DOKTER UMUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202686', 'nama' => 'PANJI MARIJAN FIRDAUS, S.Farm', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'TENAGA TEKNIS KEFARMASIAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242938', 'nama' => 'PARIDA PEBRUANTI, S. KEP., NERS', 'unit_kerja' => 'INSTALASI GAWAT DARURAT', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20050919', 'nama' => 'PATRICIA LUMINDA BATUBARA, DR', 'unit_kerja' => 'DOKTER JAGA', 'posisi_pekerjaan' => 'DOKTER UMUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253037', 'nama' => 'PINA HARYANTI., AMD.FARM', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'TENAGA TEKNIS KEFARMASIAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20061051', 'nama' => 'PUJI ASTUTI, AMK', 'unit_kerja' => 'DUTY OFFICER', 'posisi_pekerjaan' => 'DUTY OFFICER', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20202745', 'nama' => 'PUTRY SUSILOWATI, Am.Keb', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF BIDAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202689', 'nama' => 'QORI FADILAH, SST', 'unit_kerja' => 'KAMAR BERSALIN', 'posisi_pekerjaan' => 'STAF BIDAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20222900', 'nama' => 'RACHEL JIHAN KAMILA, S.M', 'unit_kerja' => 'KASIR', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253032', 'nama' => 'RAFIKA ZAHRA, S.KEP., NERS', 'unit_kerja' => 'NS 1', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253051', 'nama' => 'RAHAYU AFIAH SURUR, DR', 'unit_kerja' => 'RAWAT INAP', 'posisi_pekerjaan' => 'KEPALA RAWAT INAP', 'profesi' => 'NON MEDIS', 'jabatan' => 'KEPALA UNIT/ INSTALASI'],
        ]);

        $karyawan = array_merge($karyawan, [
            ['nip' => '20253064', 'nama' => 'RAHAYU PUSPAWANDARI, DR', 'unit_kerja' => 'DOKTER JAGA', 'posisi_pekerjaan' => 'DOKTER UMUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253086', 'nama' => 'RAIMOND ANDROMEGA,DR., M.P.H', 'unit_kerja' => 'CASEMIX', 'posisi_pekerjaan' => 'DOKTER CASEMIX', 'profesi' => 'NON MEDIS', 'jabatan' => 'KEPALA'],
            ['nip' => '20253058', 'nama' => 'RAKEUN MAYANG MUTIARA, S.FARM', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'TENAGA TEKNIS KEFARMASIAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212773', 'nama' => 'RANDILUFTI SANTOSO, Dr', 'unit_kerja' => 'DOKTER JAGA', 'posisi_pekerjaan' => 'DOKTER UMUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192558', 'nama' => 'RANTI AGUSTIANI, AMd Kep', 'unit_kerja' => 'ICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192618', 'nama' => 'RARAS OCVERTYA., A. MD', 'unit_kerja' => 'ADMISSION', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20091320', 'nama' => 'RATNA NURHAYATI, AMK', 'unit_kerja' => 'NICU & PICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212788', 'nama' => 'RATNA PURI, AMD KEP', 'unit_kerja' => 'NS 4', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192541', 'nama' => 'RATU SELPI CAHYANTI, AMD AK', 'unit_kerja' => 'INSTALASI LABORATORIUM', 'posisi_pekerjaan' => 'ANALIS LABORATORIUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192650', 'nama' => 'REGAWA PARRIKESIT., A. MD', 'unit_kerja' => 'ADMISSION', 'posisi_pekerjaan' => 'KOORDINATOR ADMINISTRASI PASIEN', 'profesi' => 'NON MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20192561', 'nama' => 'RENA FARHAH, AMD Kep', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20040674', 'nama' => 'RENI CAHYANTI, AM.KEB', 'unit_kerja' => 'KAMAR BERSALIN', 'posisi_pekerjaan' => 'STAF BIDAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20081172', 'nama' => 'RENY MULYASARI, AMK', 'unit_kerja' => 'NS 6', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB NS 6', 'profesi' => 'MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20202755', 'nama' => 'RESTI FEBRIYANTI, AMd Kes', 'unit_kerja' => 'INSTALASI LABORATORIUM', 'posisi_pekerjaan' => 'ANALIS LABORATORIUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20020417', 'nama' => 'RETNA RAHAYUNINGSIH, AM. KEB', 'unit_kerja' => 'KAMAR BERSALIN', 'posisi_pekerjaan' => 'STAF BIDAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20172355', 'nama' => 'RHISMA HILDA PRAWITA, STr. KL', 'unit_kerja' => 'KESEHATAN LINGKUNGAN', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB SANITASI', 'profesi' => 'NON MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20222898', 'nama' => 'RICKY ADI PRATAMA, SM', 'unit_kerja' => 'KASIR', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202677', 'nama' => 'RIKA RAMDAYANTI, SM', 'unit_kerja' => 'AKUNTANSI & PAJAK', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20182412', 'nama' => 'RINA AYU APRILIANTI,  AMD AK', 'unit_kerja' => 'INSTALASI LABORATORIUM', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20172252', 'nama' => 'RINA REDAWATI,AM.Keb', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF BIDAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253061', 'nama' => 'RINDI KOMALASARI, S.KEP. NERS', 'unit_kerja' => 'INSTALASI GAWAT DARURAT', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20081313', 'nama' => 'RISANTI MARYONO, S. Kep., Ners', 'unit_kerja' => 'INSTALASI GAWAT DARURAT', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253012', 'nama' => 'RISA NUR FADILLA., S. Tr. Kes', 'unit_kerja' => 'INSTALASI LABORATORIUM', 'posisi_pekerjaan' => 'ANALIS LABORATORIUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20040741', 'nama' => 'RITA FITRIANI, AMKG', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'TERAPIS GIGI & MULUT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20040827', 'nama' => 'RIZA SUKMA SARI, AMD', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'TENAGA TEKNIS KEFARMASIAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20172374', 'nama' => 'RIZKI WICAKSONO, Dr', 'unit_kerja' => 'DOKTER JAGA', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB HEMODIALISA', 'profesi' => 'MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '19960285', 'nama' => 'R. MAMAT HERMANSYAH, S.Tr.Kes', 'unit_kerja' => 'REHABILITASI MEDIK', 'posisi_pekerjaan' => 'FISIOTERAPI', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20182431', 'nama' => 'ROKA MALLA, AMD FT', 'unit_kerja' => 'KTKA', 'posisi_pekerjaan' => 'FISIOTERAPI', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20020428', 'nama' => 'ROSALIA BR. PURBA, S. KEP., Ns', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '19940117', 'nama' => 'RUSLI', 'unit_kerja' => 'LEGAL', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20232920', 'nama' => 'RYAN KHUNAM ALAMHARI, S. Farm', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'TENAGA TEKNIS KEFARMASIAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20222887', 'nama' => 'SAHILA RIZKIA, AMd Gz', 'unit_kerja' => 'INSTALASI GIZI', 'posisi_pekerjaan' => 'AHLI GIZI PRODUKSI', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242980', 'nama' => 'SAINT RYALIN FIRDAUS, AMD. KEB', 'unit_kerja' => 'KAMAR BERSALIN', 'posisi_pekerjaan' => 'STAF BIDAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253055', 'nama' => 'SALMA AHSANIAWATI, S.KEP., NERS', 'unit_kerja' => 'NS 3', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253056', 'nama' => 'SALSABILLA AULIA JATMIKO,S. TR. KEP., NERS', 'unit_kerja' => 'INSTALASI GAWAT DARURAT', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20020434', 'nama' => 'SAMSIAH, S.KEP.,NERS', 'unit_kerja' => 'NICU & PICU', 'posisi_pekerjaan' => 'KOORDINATOR NICU & PICU', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20040801', 'nama' => 'SAMSON FEMI EFFENDI', 'unit_kerja' => 'LOGISTIK UMUM', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212763', 'nama' => 'SANDY PERMANA', 'unit_kerja' => 'KASIR', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20040754', 'nama' => 'SANI INDRAYANA, AMAK', 'unit_kerja' => 'INSTALASI LABORATORIUM', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '19950207', 'nama' => 'SARI ROHATI, AMK', 'unit_kerja' => 'HEMODIALISA', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20111609', 'nama' => 'SARSILAH, S.Kep., Ners', 'unit_kerja' => 'ICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253079', 'nama' => 'SATRIO GILANG PRATAMA, S.KEP., NERS', 'unit_kerja' => 'NS 3', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192583', 'nama' => 'SEKAR AYU WULANDARI, AMD KEP', 'unit_kerja' => 'NS 8', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202685', 'nama' => 'SELLY LESTIANA, S.Si.,Apt', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'APOTEKER', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202694', 'nama' => 'SENY SETIAWANTI, AMD KEP', 'unit_kerja' => 'ICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20091380', 'nama' => 'SEPTIAN NUGROHO, AMD. RAD', 'unit_kerja' => 'INSTALASI RADIOLOGI', 'posisi_pekerjaan' => 'KOORDINATOR RADIOLOGI', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20253029', 'nama' => 'SETIADI, DR', 'unit_kerja' => 'DOKTER JAGA', 'posisi_pekerjaan' => 'DOKTER UMUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20222846', 'nama' => 'SHINTA KUSUMA WARDANI, S.KEP.,NERS', 'unit_kerja' => 'NS 7', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192557', 'nama' => 'SINTIA RESTU DEVI, AMd Kep', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253048', 'nama' => 'SISCA AMALIAH', 'unit_kerja' => 'CASEMIX', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20202712', 'nama' => 'SISCHA, S. Farm', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'TENAGA TEKNIS KEFARMASIAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
        ]);

        $karyawan = array_merge($karyawan, [
            ['nip' => '20232918', 'nama' => 'SITA AISAH ANGGITA, S. SOS', 'unit_kerja' => 'MARKETING', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20040852', 'nama' => 'SITAH UMU HAKIM, AMK', 'unit_kerja' => 'DIVISI KEPERAWATAN', 'posisi_pekerjaan' => 'KOORDINATOR CLINICAL INSTRUKTOR', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20182495', 'nama' => 'SITI NUR HIDAYAH, Amd Kep', 'unit_kerja' => 'NS 4', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242931', 'nama' => 'SITI NURMILAH, S. KEP., NERS', 'unit_kerja' => 'NS 7', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253067', 'nama' => 'SITI SARI WULANDARI, S.KEP., NERS', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20222881', 'nama' => 'SOBUR SETIAWAN, S.KEP.,NERS', 'unit_kerja' => 'NS 6', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20040795', 'nama' => 'SOEPARNO, AMd.Perkes., S.MIK', 'unit_kerja' => 'REKAM MEDIS', 'posisi_pekerjaan' => 'KOORDINATOR REKAM MEDIS', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20192624', 'nama' => 'SRI ANNISA NURAENI, AMK', 'unit_kerja' => 'NS 4', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20121748', 'nama' => 'SRI FATMIANI, AMD', 'unit_kerja' => 'INSTALASI GIZI', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212765', 'nama' => 'SRI LESTARI DAMAYANTI, S.Kep., Ners', 'unit_kerja' => 'NS 4', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20172357', 'nama' => 'SRI NURHAYATI, AMAK', 'unit_kerja' => 'INSTALASI LABORATORIUM', 'posisi_pekerjaan' => 'ANALIS LABORATORIUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20162170', 'nama' => 'SRI WAHYULI., A. MD', 'unit_kerja' => 'KASIR', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20101419', 'nama' => 'SRI YULIANI, S.KEP., NERS', 'unit_kerja' => 'NS 3', 'posisi_pekerjaan' => 'KOORDINATOR RAWAT INAP YASMIN & AZALIA', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '19960284', 'nama' => 'SUGIONO', 'unit_kerja' => 'LAUNDRY', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253042', 'nama' => 'SUHAERIYAH, S.Farm', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'TENAGA TEKNIS KEFARMASIAN', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253080', 'nama' => 'SUHERMAN, S. KEP', 'unit_kerja' => 'KAMAR OPERASI', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212834', 'nama' => 'SUMAYYAH FITRI KARIMAH, AMd Keb', 'unit_kerja' => 'KAMAR BERSALIN', 'posisi_pekerjaan' => 'STAF BIDAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '19950219', 'nama' => 'SUNARDI', 'unit_kerja' => 'LAUNDRY', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '19950176', 'nama' => 'SUPADMI, AMAK', 'unit_kerja' => 'INSTALASI LABORATORIUM', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20192616', 'nama' => 'SURYADI, SE', 'unit_kerja' => 'KEUANGAN', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20121845', 'nama' => 'SYAIDA ROHMANI, Amd FT', 'unit_kerja' => 'REHABILITASI MEDIK', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20202682', 'nama' => 'TANTI NURIYANTI, S.Kep', 'unit_kerja' => 'KAMAR OPERASI', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB SHIFT KAMAR OPERASI', 'profesi' => 'MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20162109', 'nama' => 'TANTY HERDIYANI. Dr. Sp.PK', 'unit_kerja' => 'INSTALASI LABORATORIUM', 'posisi_pekerjaan' => 'DOKTER PENANGGUNG JAWAB LABORATORIUM', 'profesi' => 'MEDIS', 'jabatan' => 'DOKTER SPESIALIS'],
            ['nip' => '20232926', 'nama' => 'TARY SHINTYA SOPANDI., S. PD', 'unit_kerja' => 'AKUNTANSI & PAJAK', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242970', 'nama' => 'TASYA PUTRI OKTAVIA, AMD. AK', 'unit_kerja' => 'INSTALASI LABORATORIUM', 'posisi_pekerjaan' => 'ANALIS LABORATORIUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '19970291', 'nama' => 'TETRIARIN CH. DARMO, AMK', 'unit_kerja' => 'DUTY OFFICER', 'posisi_pekerjaan' => 'DUTY OFFICER', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '19950116', 'nama' => 'TITA ANGGANA PUSPA', 'unit_kerja' => 'MARKETING', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20101451', 'nama' => 'TRI ARYANI., A. MD', 'unit_kerja' => 'ADMISSION', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20061048', 'nama' => 'TRI AYU AMALIA., A. MD', 'unit_kerja' => 'AKUNTANSI & PAJAK', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20111631', 'nama' => 'TRISNA UMBARA PRIASMARA., A. MD', 'unit_kerja' => 'ADMISSION', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20071128', 'nama' => 'UJANG RUKMA', 'unit_kerja' => 'MAINTENANCE', 'posisi_pekerjaan' => 'STAFF IPSRS', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20242967', 'nama' => 'ULPATUL MILLAH, S. FARM., APT', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'APOTEKER', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20222886', 'nama' => 'UMAR BAIDHOWI., S. KOM', 'unit_kerja' => 'IT', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20252995', 'nama' => 'VERAWATY., M. FARM., APT', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB LOGISTIK FARMASI', 'profesi' => 'MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20253013', 'nama' => 'VIDYAZAHRA ARASHA DEDI., A.MD. AK', 'unit_kerja' => 'INSTALASI LABORATORIUM', 'posisi_pekerjaan' => 'ANALIS LABORATORIUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212775', 'nama' => 'VIVI AHMALIA, S. KEP. NERS', 'unit_kerja' => 'NS 1', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20040809', 'nama' => 'WAWAN PURWANTO., S. KOM', 'unit_kerja' => 'ADMISSION', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20172383', 'nama' => 'WIDA KARANTINA, AMK', 'unit_kerja' => 'NS 7', 'posisi_pekerjaan' => 'PENANGGUNG JAWAB NS 7', 'profesi' => 'MEDIS', 'jabatan' => 'PENANGGUNG JAWAB'],
            ['nip' => '20050985', 'nama' => 'WIDIAWATI, S.Kep.,Ners', 'unit_kerja' => 'ICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212778', 'nama' => 'WIDYA OKTAVYANA, A.MD.KEP', 'unit_kerja' => 'PERINATOLOGI', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '19960267', 'nama' => 'WIJIL RUMANTINI, AMd Rad', 'unit_kerja' => 'INSTALASI RADIOLOGI', 'posisi_pekerjaan' => 'RADIOGRAFER', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20172348', 'nama' => 'WINA NATA PUTRI, S. KEP. NS', 'unit_kerja' => 'NICU & PICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20212772', 'nama' => 'WISESA NANDIWARDHANA, DR', 'unit_kerja' => 'DOKTER JAGA', 'posisi_pekerjaan' => 'DOKTER UMUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253046', 'nama' => 'WISNA MERIZKY, DR', 'unit_kerja' => 'DOKTER JAGA', 'posisi_pekerjaan' => 'DOKTER UMUM', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20111698', 'nama' => 'WITA ROSTANIA,.DR, Sp.A', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'DOKTER SPESIALIS', 'profesi' => 'MEDIS', 'jabatan' => 'DOKTER SPESIALIS'],
            ['nip' => '20172347', 'nama' => 'WULAN SARI, AMK', 'unit_kerja' => 'NS 8', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20131904', 'nama' => 'YANA HERMAWAN, SE', 'unit_kerja' => 'KASIR', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '19980340', 'nama' => 'YANTI HAPTIANI, S.Kep.,Ners', 'unit_kerja' => 'NS 7', 'posisi_pekerjaan' => 'KOORDINATOR RAWAT INAP NINDA & ARDELIA', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20253083', 'nama' => 'YENIMANDEZA PUTRY, S. KEP., NERS', 'unit_kerja' => 'NS 1', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20061036', 'nama' => 'YENI ROHENDA, AMK', 'unit_kerja' => 'ICU', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20050891', 'nama' => 'YENI YULIA, AMK', 'unit_kerja' => 'NS 1', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253057', 'nama' => 'YOGI, S.FARM', 'unit_kerja' => 'INSTALASI FARMASI', 'posisi_pekerjaan' => 'TENAGA TEKNIS KEFARMASIAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20081310', 'nama' => 'YOSE SLAMET SAPUTRA, SE', 'unit_kerja' => 'KEUANGAN', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20050927', 'nama' => 'YULIANA, AMK', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'KOORDINATOR RAWAT JALAN & MCU, HD', 'profesi' => 'MEDIS', 'jabatan' => 'KOORDINATOR'],
            ['nip' => '20242966', 'nama' => 'YULISA FADHILLAH, S. Tr. Ds', 'unit_kerja' => 'MARKETING', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20081267', 'nama' => 'YULITA DIAN LESTARI, AM.KEB', 'unit_kerja' => 'KAMAR BERSALIN', 'posisi_pekerjaan' => 'STAF BIDAN', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253075', 'nama' => 'YUNITA SARI, S.KEP.,NERS', 'unit_kerja' => 'RAWAT JALAN', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20222879', 'nama' => 'YUSTIKA DAMAYANTI, S.KEP.,NERS', 'unit_kerja' => 'NS 6', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20101418', 'nama' => 'YUYUN POMADINI, AMK', 'unit_kerja' => 'PERINATOLOGI', 'posisi_pekerjaan' => 'STAF PERAWAT', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253098', 'nama' => 'ZALLITA SAKTYA HARARI, A.MD. RAD', 'unit_kerja' => 'INSTALASI RADIOLOGI', 'posisi_pekerjaan' => 'STAFF', 'profesi' => 'MEDIS', 'jabatan' => 'STAFF'],
            // Manajemen & Direktur
            ['nip' => '20141969', 'nama' => 'DIENI ANANDA PUTRI, DR, MARS', 'unit_kerja' => 'MUTU', 'posisi_pekerjaan' => 'MANAGER MUTU', 'profesi' => 'MEDIS', 'jabatan' => 'MANAGER'],
            ['nip' => '20061005', 'nama' => 'GARCINIA SATIVA FIZRIA SETIADI , Dr, MKM', 'unit_kerja' => 'PENUNJANG MEDIK', 'posisi_pekerjaan' => 'MANAGER PENUNJANG MEDIK', 'profesi' => 'MEDIS', 'jabatan' => 'MANAGER'],
            ['nip' => '20253017', 'nama' => 'INDRA THALIB, BSN., MM', 'unit_kerja' => 'SDM', 'posisi_pekerjaan' => 'MANAGER SDM', 'profesi' => 'NON MEDIS', 'jabatan' => 'MANAGER'],
            ['nip' => '20253030', 'nama' => 'IRMA RISMAYANTY, dr, MM', 'unit_kerja' => 'DIREKTUR', 'posisi_pekerjaan' => 'DIREKTUR RS', 'profesi' => 'NON MEDIS', 'jabatan' => 'DIREKTUR'],
            ['nip' => '19950015', 'nama' => 'LAILA AZRA, DRA.', 'unit_kerja' => 'PT. ASP', 'posisi_pekerjaan' => 'KOMISARIS PT. ASP', 'profesi' => 'NON MEDIS', 'jabatan' => 'PRESIDEN KOMISARIS'],
            ['nip' => '20253062', 'nama' => 'LILI MARLIANI, DR., MARS', 'unit_kerja' => 'PELAYANAN MEDIK', 'posisi_pekerjaan' => 'MANAGER PELAYANAN MEDIK', 'profesi' => 'MEDIS', 'jabatan' => 'MANAGER'],
            ['nip' => '20212767', 'nama' => 'METRI JULIANTI, SE', 'unit_kerja' => 'KEUANGAN', 'posisi_pekerjaan' => 'MANAGER KEUANGAN', 'profesi' => 'NON MEDIS', 'jabatan' => 'MANAGER'],
            ['nip' => '20071107', 'nama' => 'M. RANGGA ADITYA', 'unit_kerja' => 'PT. ASP', 'posisi_pekerjaan' => 'DIREKTUR PT. ASP', 'profesi' => 'NON MEDIS', 'jabatan' => 'DIREKTUR'],
            ['nip' => '20242964', 'nama' => 'MUHAMAD MIFTAHUDIN., M. KOM', 'unit_kerja' => 'IT', 'posisi_pekerjaan' => 'MANAGER IT', 'profesi' => 'NON MEDIS', 'jabatan' => 'MANAGER'],
            ['nip' => '20242957', 'nama' => 'RIA FAJARROHMI, SE', 'unit_kerja' => 'AKUNTANSI & PAJAK', 'posisi_pekerjaan' => 'SUPERVISOR AKUNTING & PAJAK', 'profesi' => 'NON MEDIS', 'jabatan' => 'KEPALA'],
            ['nip' => '20111600', 'nama' => 'RIYADI MAULANA,SH., MH., CLA., CCD', 'unit_kerja' => 'LEGAL', 'posisi_pekerjaan' => 'MANAGER LEGAL', 'profesi' => 'NON MEDIS', 'jabatan' => 'MANAGER'],
            ['nip' => '19940189', 'nama' => 'SENI MAULIDA FITALOKA. S.Kep,Ns, M.Kep', 'unit_kerja' => 'DIVISI KEPERAWATAN', 'posisi_pekerjaan' => 'MANAGER KEPERAWATAN', 'profesi' => 'MEDIS', 'jabatan' => 'MANAGER'],
            ['nip' => '20020462', 'nama' => 'SITI KHOIRIAH', 'unit_kerja' => 'SEKRETARIAT', 'posisi_pekerjaan' => 'SEKRETARIS DIREKTUR PT. ASP', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
            ['nip' => '20253070', 'nama' => 'THORIQ FARIED ISHAQ, S.I. KOM', 'unit_kerja' => 'UMUM', 'posisi_pekerjaan' => 'MANAGER UMUM', 'profesi' => 'NON MEDIS', 'jabatan' => 'MANAGER'],
            ['nip' => '20253008', 'nama' => 'TUMPAS BANGKIT PRAYUDA., SE', 'unit_kerja' => 'MARKETING', 'posisi_pekerjaan' => 'MANAGER MARKETING', 'profesi' => 'NON MEDIS', 'jabatan' => 'MANAGER'],
            ['nip' => '20242988', 'nama' => 'VERONIKA RINI HANDAYANI., A. MD', 'unit_kerja' => 'SEKRETARIAT', 'posisi_pekerjaan' => 'SEKRETARIS DIREKTUR PT.ASP', 'profesi' => 'NON MEDIS', 'jabatan' => 'STAFF'],
        ]);

        foreach ($karyawan as $data) {
            $parsed = $this->parseNama($data['nama']);
            $username = $this->makeUniqueUsername($parsed['username'], $usedUsernames);

            User::updateOrCreate(
                ['nip' => $data['nip']],
                [
                    'first_name'       => $parsed['firstName'],
                    'last_name'        => $parsed['lastName'],
                    'username'         => $username,
                    'nip'              => $data['nip'],
                    'password'         => Hash::make('rsazra'),
                    'unit_kerja'       => $data['unit_kerja'],
                    'posisi_pekerjaan' => $data['posisi_pekerjaan'],
                    'profesi'          => $data['profesi'],
                    'jabatan'          => $data['jabatan'],
                    'role'             => 'user',
                    'priority_level'   => 0,
                ]
            );
        }

        $this->command->info('Seeder KaryawanSeeder selesai: ' . count($karyawan) . ' data diproses.');
    }
}
